# Generated by Django 5.1 on 2024-10-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetup', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static\\default_prfile.jpg', upload_to='profile_images'),
        ),
    ]
