# Generated by Django 5.1 on 2024-10-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersetup', '0006_remove_profile_bio_profile_ap_biology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hi!'),
        ),
    ]
